### ISSUE TITLE
--localOnly false not working properly

### ISSUE THREAD

**Issue by chourmovs** [dhicks6345789/web-console#1]
```
sudo webconsole --port 9999 --localOnly false --start
Webconsole - starting webserver. "webconsole --help" for more details.
Web server limited to localhost only.
Web server using webroot /etc/webconsole/www, taskroot /etc/webconsole/tasks.
Web server available at: http://localhost:9999/
```

Thank you for your help

**Comment by dhicks6345789** [comment]
Many thanks for reporting issue #1! I'd added a call to lowerCase() to make all user-passed options lower case, but forgotten to change the "localOnly" string to actually be all lowercase, so the arguments never matched. Should, hopefully, be fixed now, plus I've added a bit more information to be displayed when --debug mode is set to display version number and all configured arguments.

I've re-built the executable, you should be able to find the binary for download on this page:

https://github.com/dhicks6345789/web-console/blob/master/docs/INSTALLATION.md

Or, if you're on Linux, this should (hopefully...) do an install of that version:

curl -s https://www.sansay.co.uk/web-console/install.sh | sudo bash -s -- nightly

**Comment by chourmovs** [comment]
thank you, i ll give it a try even if i found my way using shellinabox

**Comment by dhicks6345789** [comment]
Ah, Shellinabox seems like a good project - I've added a documentation page listing some alternatives and added it there:

https://github.com/dhicks6345789/web-console/blob/master/docs/ALTERNATIVES.md

Thanks for your help.
